"""
schemas.py — Pydantic request/response models exposed by the
FastAPI backend. Kept separate from ``models/schemas.py`` (which holds
service-layer types) because the wire-format may diverge from the
internal types (extra fields, different defaults, snake_case → camelCase
later, etc.).
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


# ──────────────────────────────────────────────────────────────────────
# Auth
# ──────────────────────────────────────────────────────────────────────
class OtpRequest(BaseModel):
    phone: str = Field(min_length=10, max_length=15)
    language: str = Field(
        default="en",
        description="Candidate language code; localises the OTP SMS template.",
    )


class OtpRequestResponse(BaseModel):
    ok: bool
    message: str
    demo_otp: Optional[str] = Field(
        default=None,
        description=(
            "Only populated when DEMO_MODE=1 — shows the OTP that the "
            "next /verify call will accept. Never set in production."
        ),
    )


class OtpVerify(BaseModel):
    phone: str
    otp: str = Field(min_length=4, max_length=6)


class OtpVerifyResponse(BaseModel):
    ok: bool
    token: str = Field(description="Bearer token used in subsequent requests.")
    candidate_phone: str


# ──────────────────────────────────────────────────────────────────────
# Sessions
# ──────────────────────────────────────────────────────────────────────
class CreateSessionRequest(BaseModel):
    role: str = Field(description="Role key, e.g. 'housekeeping'.")
    language: str = Field(description="Short language code, e.g. 'hi'.")
    candidate_name: str = Field(min_length=1, max_length=80)
    candidate_phone: str = Field(
        default="",
        description="Candidate's phone (from /auth/otp/verify). Optional in demo.",
    )
    recruiter_email: str = Field(
        default="",
        description="Where the final report email should be sent.",
    )


class QuestionInfo(BaseModel):
    """Current question — what the client should display + play."""
    text: str
    audio_url: str = Field(
        description=(
            "Relative URL the client can GET to download the WAV. "
            "Lazy-generated by the server on first request."
        ),
    )


class SessionStateView(BaseModel):
    """Server view of a session, returned by most endpoints."""
    session_id: str
    stage: str
    progress: float = Field(ge=0.0, le=1.0)
    is_terminal: bool = False
    candidate_name: str
    role: str
    language: str
    current_question: Optional[QuestionInfo] = None
    # Only populated after /finalize
    final_report_url: Optional[str] = None


class AnswerResponse(SessionStateView):
    """Response from POST /sessions/{id}/answer — adds the transcript
    of what the candidate just said (for the chat-bubble UI)."""
    last_transcript: str = ""


# ──────────────────────────────────────────────────────────────────────
# Health / config
# ──────────────────────────────────────────────────────────────────────
class HealthResponse(BaseModel):
    ok: bool
    sarvam_ok: bool
    db_ok: bool
    demo_mode: bool


class RoleOption(BaseModel):
    key: str
    title: str


class LanguageOption(BaseModel):
    code: str
    label: str
    bcp47: str


class ConfigResponse(BaseModel):
    roles: list[RoleOption]
    languages: list[LanguageOption]
    behavioral_question_count: int
    profile_question_count: int


# ──────────────────────────────────────────────────────────────────────
# Recruiter report
# ──────────────────────────────────────────────────────────────────────
class ReportResponse(BaseModel):
    session_id: str
    candidate_name: str
    role: str
    language: str
    finalized_at: Optional[float]
    evaluation: Optional[dict]
    behavioral_eval: Optional[dict]
    profile: Optional[dict]
    enrichment: Optional[dict]
    questions_asked: list[str]
    transcripts: list[str]
    behavioral_transcripts: list[dict]
